version: '2'
services:
  dse:
    image: "datastax/dse-server:6.0.2"
    environment:
      - DS_LICENSE=accept
    # Allow DSE to lock memory with mlock
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1
  studio:
    image: "datastax/dse-studio:6.0.0"
    environment:
      - DS_LICENSE=accept
    ports:
      - 9091:9091